### ISSUE TITLE
System-wide connections

### ISSUE THREAD

**Issue by laurivosandi** [camptocamp/puppet-networkmanager#11]
Hello,

it seems there is no way to provide password for WPA2 connections from your module? It's easy as replacing following:

```
[802-11-wireless-security]
key-mgmt=wpa-psk
auth-alg=open
psk-flags=1
```

with this:

```
[802-11-wireless-security]
key-mgmt=wpa-psk
auth-alg=open
psk=the-password-goes-here
```

More details here: http://lauri.vosandi.com/cfgmgmt/network-manager-system-connections.html

**Comment by v6sa** [comment]
For system-wide connections also remove permissions=... lines

**Comment by mcanevet** [comment]
@v6sa PR welcome

**Comment by JGodin-C2C** [comment]
No news. 
Closing.
